create table cla_patient_medical_histories(
   company_id                     number(20) not null,
   patient_medical_history_id     number not null,
   patient_medical_history_number varchar2(10) not null,
   last_name                      varchar2(50 char) not null,
   first_name                     varchar2(50 char) not null,
   patronymic                     varchar2(50 char) not null,
   passport_number                varchar2(9) not null,
   birth_date                     date not null,
   gender                         varchar2(1) not null,
   phone                          varchar2(17) not null,
   height                         number(3),
   weight                         number(4, 1),
   address                        varchar2(200 char),
   job                            varchar2(100 char),
   created_by                     number(20)  not null,
   created_on                     timestamp with local time zone not null,
   modified_by                    number(20)  not null,
   modified_on                    timestamp with local time zone not null,
   constraint cla_patient_medical_histories_pk primary key (company_id, patient_medical_history_id) using index tablespace GWS_INDEX,
   constraint cla_patient_medical_histories_f1 foreign key (company_id, created_by) references md_users(company_id, user_id),
   constraint cla_patient_medical_histories_f2 foreign key (company_id, modified_by) references md_users(company_id, user_id),
   constraint cla_patient_medical_histories_u1 unique (patient_medical_history_number) using index tablespace GWS_INDEX,
   constraint cla_patient_medical_histories_u2 unique (passport_number) using index tablespace GWS_INDEX,
   constraint cla_patient_medical_histories_c1 check (regexp_like(passport_number, '^[A-Z]{2}\d{7}$')),
   constraint cla_patient_medical_histories_c2 check ((height is null and weight is null) or (height is not null and weight is not null))
) tablespace GWS_DATA;
